[package]
name = "mate-tool-agent"
version.workspace = true
edition.workspace = true

[dependencies]
mate-tool-api = { workspace = true }
rig = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
