[package]
name = "mate-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
fastrand = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
mate-tool-agent = { workspace = true }
mate-tool-api = { workspace = true }
mate-tool-fs = { workspace = true }
mate-tool-http = { workspace = true }
mate-tool-skills = { workspace = true }
reqwest = { workspace = true }
rig = { workspace = true, features = ["reqwest", "rustls", "agent"] }
serde = { workspace = true }
serde_json = { workspace = true }
slotmap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }

[dev-dependencies]
rig = { workspace = true, features = ["test-utils"] }
tempfile = { workspace = true }
wiremock = { workspace = true }
