[package]
name = "mate-tui"
version.workspace = true
edition.workspace = true

[dependencies]
crossterm = { workspace = true }
dunce = { workspace = true }
futures = { workspace = true }
mate-core = { workspace = true }
mate-tool-api = { workspace = true }
ratatui = { workspace = true }
ratatui-textarea = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
