// @generated by `just gen-model-catalog` (crates/xtask-model-catalog) from
// anomalyco/models.dev@552ba9d996a628e38a721ff68e9a5c7f7e5fcfd9. Do not edit by hand: rerun the recipe instead.

use super::{CatalogBackend, ModelEntry};
use crate::cost::ModelRate;

#[rustfmt::skip]
pub(super) const CATALOG: &[ModelEntry] = &[
    ModelEntry {
        id: "MiniMaxAI/MiniMax-M2",
        display_name: "MiniMax-M2",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 1.2,
        }),
    },
    ModelEntry {
        id: "MiniMaxAI/MiniMax-M2.1",
        display_name: "MiniMax-M2.1",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 1.2,
        }),
    },
    ModelEntry {
        id: "MiniMaxAI/MiniMax-M2.5",
        display_name: "MiniMax-M2.5",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 1.2,
        }),
    },
    ModelEntry {
        id: "MiniMaxAI/MiniMax-M2.7",
        display_name: "MiniMax-M2.7",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 1.2,
        }),
    },
    ModelEntry {
        id: "MiniMaxAI/MiniMax-M3",
        display_name: "MiniMax-M3",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 1.2,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen2.5-Coder-32B-Instruct",
        display_name: "Qwen2.5-Coder-32B-Instruct",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.06,
            output_per_million: 0.2,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-235B-A22B",
        display_name: "Qwen3 235B-A22B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.2,
            output_per_million: 0.8,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-235B-A22B-Instruct-2507",
        display_name: "Qwen3 235B-A22B Instruct 2507",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.855,
            output_per_million: 2.565,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
        display_name: "Qwen3-235B-A22B-Thinking-2507",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 3.0,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-30B-A3B",
        display_name: "Qwen3 30B A3B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.12,
            output_per_million: 0.5,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-32B",
        display_name: "Qwen3 32B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.29,
            output_per_million: 0.59,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
        display_name: "Qwen3-Coder 30B-A3B Instruct",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.07,
            output_per_million: 0.26,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        display_name: "Qwen3-Coder-480B-A35B-Instruct",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 2.0,
            output_per_million: 2.0,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-Coder-Next",
        display_name: "Qwen3-Coder-Next",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.2,
            output_per_million: 1.5,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
        display_name: "Qwen3-Next-80B-A3B-Instruct",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.25,
            output_per_million: 1.0,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-Next-80B-A3B-Thinking",
        display_name: "Qwen3-Next-80B-A3B-Thinking",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 2.0,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-VL-235B-A22B-Instruct",
        display_name: "Qwen3 VL 235B A22B Instruct",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 1.5,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3-VL-235B-A22B-Thinking",
        display_name: "Qwen3 VL 235B A22B Thinking",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.98,
            output_per_million: 3.95,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3.5-122B-A10B",
        display_name: "Qwen3.5 122B-A10B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.4,
            output_per_million: 3.2,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3.5-27B",
        display_name: "Qwen3.5 27B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 2.4,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3.5-35B-A3B",
        display_name: "Qwen3.5 35B-A3B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.25,
            output_per_million: 2.0,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3.5-397B-A17B",
        display_name: "Qwen3.5-397B-A17B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.6,
            output_per_million: 3.6,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3.5-9B",
        display_name: "Qwen3.5 9B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.17,
            output_per_million: 0.25,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3.6-27B",
        display_name: "Qwen3.6 27B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.47,
            output_per_million: 3.19,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3.6-35B-A3B",
        display_name: "Qwen3.6 35B-A3B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.15,
            output_per_million: 0.95,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3.8-2.4T-A95B",
        display_name: "Qwen3.8 2.4T A95B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 2.5,
            output_per_million: 6.25,
        }),
    },
    ModelEntry {
        id: "Qwen/Qwen3.8-27B",
        display_name: "Qwen3.8 27B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.4,
            output_per_million: 3.0,
        }),
    },
    ModelEntry {
        id: "XiaomiMiMo/MiMo-V2-Flash",
        display_name: "MiMo-V2-Flash",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.1,
            output_per_million: 0.3,
        }),
    },
    ModelEntry {
        id: "XiaomiMiMo/MiMo-V2.5",
        display_name: "MiMo-V2.5",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.4,
            output_per_million: 2.0,
        }),
    },
    ModelEntry {
        id: "XiaomiMiMo/MiMo-V2.5-Pro",
        display_name: "MiMo-V2.5-Pro",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 1.0,
            output_per_million: 3.0,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-R1",
        display_name: "DeepSeek-R1",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.7,
            output_per_million: 2.5,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-R1-0528",
        display_name: "DeepSeek-R1-0528",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 3.0,
            output_per_million: 5.0,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V3",
        display_name: "DeepSeek-V3",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.4,
            output_per_million: 1.3,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V3-0324",
        display_name: "DeepSeek V3 0324",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.27,
            output_per_million: 1.12,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V3.1",
        display_name: "DeepSeek-V3.1",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.27,
            output_per_million: 1.0,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V3.2",
        display_name: "DeepSeek-V3.2",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.28,
            output_per_million: 0.4,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V4-Flash",
        display_name: "DeepSeek V4 Flash",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.14,
            output_per_million: 0.28,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V4-Flash-0731",
        display_name: "DeepSeek V4 Flash 0731",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.14,
            output_per_million: 0.28,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
        display_name: "DeepSeek V4 Flash Vision Exp",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.44,
            output_per_million: 1.32,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V4-Pro",
        display_name: "DeepSeek V4 Pro",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.435,
            output_per_million: 0.87,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V4-Pro-0813",
        display_name: "DeepSeek V4 Pro 0813",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 1.32,
            output_per_million: 3.96,
        }),
    },
    ModelEntry {
        id: "deepseek-ai/DeepSeek-V4.1-Flash",
        display_name: "DeepSeek V4.1 Flash",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 1.2,
        }),
    },
    ModelEntry {
        id: "google/gemma-3-12b-it",
        display_name: "Gemma 3 12B IT",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.05,
            output_per_million: 0.15,
        }),
    },
    ModelEntry {
        id: "google/gemma-3-27b-it",
        display_name: "Gemma 3 27B IT",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.08,
            output_per_million: 0.16,
        }),
    },
    ModelEntry {
        id: "google/gemma-3-4b-it",
        display_name: "Gemma 3 4B IT",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.05,
            output_per_million: 0.1,
        }),
    },
    ModelEntry {
        id: "google/gemma-4-26B-A4B-it",
        display_name: "Gemma 4 26B A4B IT",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.13,
            output_per_million: 0.4,
        }),
    },
    ModelEntry {
        id: "google/gemma-4-31B-it",
        display_name: "Gemma 4 31B IT",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.14,
            output_per_million: 0.4,
        }),
    },
    ModelEntry {
        id: "meta-llama/Llama-3.1-8B-Instruct",
        display_name: "Llama-3.1-8B-Instruct",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.06,
            output_per_million: 0.06,
        }),
    },
    ModelEntry {
        id: "meta-llama/Llama-3.3-70B-Instruct",
        display_name: "Llama-3.3-70B-Instruct",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.59,
            output_per_million: 0.79,
        }),
    },
    ModelEntry {
        id: "moonshotai/Kimi-K2-Instruct",
        display_name: "Kimi-K2-Instruct",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 1.0,
            output_per_million: 3.0,
        }),
    },
    ModelEntry {
        id: "moonshotai/Kimi-K2-Instruct-0905",
        display_name: "Kimi-K2-Instruct-0905",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 1.0,
            output_per_million: 3.0,
        }),
    },
    ModelEntry {
        id: "moonshotai/Kimi-K2-Thinking",
        display_name: "Kimi-K2-Thinking",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.6,
            output_per_million: 2.5,
        }),
    },
    ModelEntry {
        id: "moonshotai/Kimi-K2.5",
        display_name: "Kimi-K2.5",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.6,
            output_per_million: 3.0,
        }),
    },
    ModelEntry {
        id: "moonshotai/Kimi-K2.6",
        display_name: "Kimi-K2.6",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.95,
            output_per_million: 4.0,
        }),
    },
    ModelEntry {
        id: "moonshotai/Kimi-K2.7-Code",
        display_name: "Kimi K2.7 Code",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.95,
            output_per_million: 4.0,
        }),
    },
    ModelEntry {
        id: "moonshotai/Kimi-K3",
        display_name: "Kimi K3",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 3.0,
            output_per_million: 15.0,
        }),
    },
    ModelEntry {
        id: "openai/gpt-oss-120b",
        display_name: "GPT OSS 120B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.25,
            output_per_million: 0.69,
        }),
    },
    ModelEntry {
        id: "openai/gpt-oss-20b",
        display_name: "GPT OSS 20B",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.1,
            output_per_million: 0.5,
        }),
    },
    ModelEntry {
        id: "stepfun-ai/Step-3.5-Flash",
        display_name: "Step 3.5 Flash",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.1,
            output_per_million: 0.3,
        }),
    },
    ModelEntry {
        id: "stepfun-ai/Step-3.7-Flash",
        display_name: "Step 3.7 Flash",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.2,
            output_per_million: 1.15,
        }),
    },
    ModelEntry {
        id: "tencent/Hy3",
        display_name: "Hy3",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.14,
            output_per_million: 0.58,
        }),
    },
    ModelEntry {
        id: "tencent/Hy4-preview",
        display_name: "Hy4 preview",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.834,
            output_per_million: 2.501,
        }),
    },
    ModelEntry {
        id: "thinkingmachines/Inkling",
        display_name: "Inkling",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 1.0,
            output_per_million: 4.05,
        }),
    },
    ModelEntry {
        id: "thinkingmachines/Inkling-Small",
        display_name: "Inkling Small",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.5,
            output_per_million: 1.2,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-4.5",
        display_name: "GLM-4.5",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.6,
            output_per_million: 2.2,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-4.5-Air",
        display_name: "GLM-4.5-Air",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.13,
            output_per_million: 0.85,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-4.5V",
        display_name: "GLM-4.5V",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.6,
            output_per_million: 1.8,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-4.6",
        display_name: "GLM-4.6",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.55,
            output_per_million: 2.2,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-4.6V-Flash",
        display_name: "GLM-4.6V-Flash",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 0.9,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-4.7",
        display_name: "GLM-4.7",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.6,
            output_per_million: 2.2,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-4.7-Flash",
        display_name: "GLM-4.7-Flash",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.0,
            output_per_million: 0.0,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-5",
        display_name: "GLM-5",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 1.0,
            output_per_million: 3.2,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-5.1",
        display_name: "GLM-5.1",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 1.0,
            output_per_million: 3.2,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-5.2",
        display_name: "GLM-5.2",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 1.4,
            output_per_million: 4.4,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-5.3",
        display_name: "GLM-5.3",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 1.4,
            output_per_million: 4.4,
        }),
    },
    ModelEntry {
        id: "zai-org/GLM-5.3-Flash",
        display_name: "GLM-5.3-Flash",
        backend: CatalogBackend::Huggingface,
        pricing: Some(ModelRate {
            input_per_million: 0.15,
            output_per_million: 0.5,
        }),
    },
    ModelEntry {
        id: "gemini-2.5-computer-use-preview-10-2025",
        display_name: "Gemini 2.5 Computer Use Preview 10-2025",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 1.25,
            output_per_million: 10.0,
        }),
    },
    ModelEntry {
        id: "gemini-2.5-flash",
        display_name: "Gemini 2.5 Flash",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 2.5,
        }),
    },
    ModelEntry {
        id: "gemini-2.5-flash-lite",
        display_name: "Gemini 2.5 Flash-Lite",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.1,
            output_per_million: 0.4,
        }),
    },
    ModelEntry {
        id: "gemini-2.5-pro",
        display_name: "Gemini 2.5 Pro",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 1.25,
            output_per_million: 10.0,
        }),
    },
    ModelEntry {
        id: "gemini-3-flash-preview",
        display_name: "Gemini 3 Flash Preview",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.5,
            output_per_million: 3.0,
        }),
    },
    ModelEntry {
        id: "gemini-3.1-flash-lite",
        display_name: "Gemini 3.1 Flash Lite",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.25,
            output_per_million: 1.5,
        }),
    },
    ModelEntry {
        id: "gemini-3.1-pro-preview",
        display_name: "Gemini 3.1 Pro Preview",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 2.0,
            output_per_million: 12.0,
        }),
    },
    ModelEntry {
        id: "gemini-3.1-pro-preview-customtools",
        display_name: "Gemini 3.1 Pro Preview Custom Tools",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 2.0,
            output_per_million: 12.0,
        }),
    },
    ModelEntry {
        id: "gemini-3.5-flash",
        display_name: "Gemini 3.5 Flash",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 1.5,
            output_per_million: 9.0,
        }),
    },
    ModelEntry {
        id: "gemini-3.5-flash-lite",
        display_name: "Gemini 3.5 Flash Lite",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 2.5,
        }),
    },
    ModelEntry {
        id: "gemini-3.6-flash",
        display_name: "Gemini 3.6 Flash",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.75,
            output_per_million: 3.75,
        }),
    },
    ModelEntry {
        id: "gemini-3.7-flash",
        display_name: "Gemini 3.7 Flash",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.75,
            output_per_million: 3.75,
        }),
    },
    ModelEntry {
        id: "gemini-3.8-flash",
        display_name: "Gemini 3.8 Flash",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.75,
            output_per_million: 3.75,
        }),
    },
    ModelEntry {
        id: "gemini-flash-latest",
        display_name: "Gemini Flash Latest",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.75,
            output_per_million: 3.75,
        }),
    },
    ModelEntry {
        id: "gemini-flash-lite-latest",
        display_name: "Gemini Flash-Lite Latest",
        backend: CatalogBackend::Gemini,
        pricing: Some(ModelRate {
            input_per_million: 0.3,
            output_per_million: 2.5,
        }),
    },
    ModelEntry {
        id: "gemma-4-26b-a4b-it",
        display_name: "Gemma 4 26B A4B IT",
        backend: CatalogBackend::Gemini,
        pricing: None,
    },
    ModelEntry {
        id: "gemma-4-31b-it",
        display_name: "Gemma 4 31B IT",
        backend: CatalogBackend::Gemini,
        pricing: None,
    },
];
